apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: movies-app
spec:
  clusterResourceWhitelist: []
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: 'movies-app'
      server: https://kubernetes.default.svc
    - namespace: 'movies-app-kafka'
      server: https://kubernetes.default.svc
  sourceRepos:
    - '*'
