apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - patch: |-
      - op: replace
        path: /spec/source/path
        value: argocd/app-config/profiles/default
    target:
      kind: Application
      name: app-config
