kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: registry
  labels:
    app: registry
spec:
  to:
    kind: Service
    name: registry-service
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect