{{- with .Values.cluster -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: broker-listeners
spec:
  secretName: cert-broker-secret
  issuerRef:
    name: {{ .name }}-cert-issuer
    kind: Issuer
  commonName: {{ .name }}-kafka
  dnsNames:
  - '*.{{ .name }}-kafka-brokers'
  - '*.{{ .name }}-kafka-brokers.{{ $.Release.Namespace }}.svc'
  - '*.{{ .name }}-kafka-brokers.{{ $.Release.Namespace }}.svc.cluster.local'
  - {{ .name }}-kafka-bootstrap
  - {{ .name }}-kafka-bootstrap.{{ $.Release.Namespace }}.svc
  - {{ .name }}-kafka-bootstrap.{{ $.Release.Namespace }}.svc.cluster.local
{{- end }}
