apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.cluster.name }}-cert-issuer
spec:
  secretName: {{ .Values.cluster.name }}-cert-issuer-secret
  issuerRef:
    name: cluster-issuer
    kind: ClusterIssuer
  commonName: {{ .Values.cluster.name }} Kafka Cluster Issuer CA
  isCA: true
