apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - ServiceAccount_kafka-ca-admin.yaml
  - RoleBinding_kafka-ca-admin.yaml
  - Certificate_cert-issuer.yaml
  - Issuer_cert-issuer.yaml
  - Job_kafka-ca-admin.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - behavior: create
    files:
      - kafka-ca-admin.sh
    name: kafka-ca-admin
    options:
      immutable: true
patches:
  - path: Kafka_broker.merge.yaml
replacements:
  - source:
      fieldPath: metadata.name
      kind: Kafka
      name: broker
    targets:
      - fieldPaths:
          - spec.commonName
        options:
          delimiter: ' '
        select:
          kind: Certificate
          name: cert-issuer
