apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - Console_kafka-console.yaml
generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
  - behavior: create
    literals:
      - clientSecret=shhh-kafka-console
    name: kafka-console-client-secret
    type: Opaque
