apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
  - patch: |-
      - op: replace
        path: /spec/installPlanApproval
        value: Manual
    target:
      kind: Subscription
