apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: movies-app-kafka
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: movies-app-kafka
    server: https://kubernetes.default.svc
  project: movies-app
  source:
    path: app-config/apps/streams-kafka
    repoURL: https://github.com/ryan-highley/rh-streams-keycloak-certmgr-gitops
    helm:
      namespace: movies-app-kafka
      releaseName: movies-app
      valuesObject:

        keycloak:
          enabled: true

        global:
          cluster:
            name: movies-app-broker

        cluster:
          spec:
            kafka:
              authorization:
                type: custom
                authorizerClass: io.strimzi.kafka.oauth.server.authorizer.KeycloakAuthorizer
                superUsers:
                  - kafka-console
              config:
                principal.builder.class: io.strimzi.kafka.oauth.server.OAuthKafkaPrincipalBuilder
                strimzi.authorization.client.id: movies-app-broker-client
                strimzi.authorization.token.endpoint.uri: https://keycloak-service.keycloak.svc:8443/realms/movies-app-broker-kafka/protocol/openid-connect/token
                strimzi.authorization.ssl.endpoint.identification.algorithm: ""
                strimzi.authorization.delegate.to.kafka.acl: "false"
                strimzi.authorization.ssl.truststore.location: /mnt/oauth-certs/ca.crt
                strimzi.authorization.ssl.truststore.type: PEM
              template:
                pod:
                  volumes:
                    - name: oauth-certs
                      secret:
                        secretName: movies-app-broker-cert-issuer-secret
                  kafkaContainer:
                    volumeMounts:
                      - name: oauth-certs
                        mountPath: /mnt/oauth-certs
              listeners:
                - name: tls
                  port: 9093
                  type: internal
                  tls: true
                  authentication:
                    type: custom
                    sasl: true
                    listenerConfig:
                      sasl.enabled.mechanisms: OAUTHBEARER
                      oauthbearer.sasl.server.callback.handler.class: io.strimzi.kafka.oauth.server.JaasServerOauthValidatorCallbackHandler
                      oauthbearer.sasl.jaas.config: |-
                        org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required
                        unsecuredLoginStringClaim_sub="thePrincipalName"
                        oauth.valid.issuer.uri="https://keycloak-service.keycloak.svc:8443/realms/movies-app-broker-kafka"
                        oauth.jwks.endpoint.uri="https://keycloak-service.keycloak.svc:8443/realms/movies-app-broker-kafka/protocol/openid-connect/certs"
                        oauth.username.claim="preferred_username"
                        oauth.ssl.truststore.location="/mnt/oauth-certs/tls.crt"
                        oauth.ssl.truststore.type="PEM";
                      connections.max.reauth.ms: 3600
                  networkPolicyPeers:
                    - namespaceSelector:
                        matchLabels:
                          kubernetes.io/metadata.name: movies-app
                - name: console
                  port: 9094
                  type: internal
                  tls: true
                  authentication:
                    type: scram-sha-512
                  networkPolicyPeers:
                    - namespaceSelector:
                        matchLabels:
                          kubernetes.io/metadata.name: kafka-console

        # nodePools:
        #   - name: controller-node-pool
        #     spec:
        #       replicas: 3
        #       roles:
        #         - controller
        #       resources:
        #         requests:
        #           memory: 256Mi
        #           cpu: 500m
        #         limits:
        #           memory: 1Gi
        #           cpu: "1"
        #       storage:
        #         type: jbod
        #         volumes:
        #           - id: 0
        #             type: persistent-claim
        #             size: 2Gi
        #             deleteClaim: false
        #       # template:
        #       #   pod:
        #       #     affinity:
        #       #       podAntiAffinity:
        #       #         requiredDuringSchedulingIgnoredDuringExecution:
        #       #           - labelSelector:
        #       #               matchExpressions:
        #       #                 - key: strimzi.io/pool-name
        #       #                   operator: In
        #       #                   values:
        #       #                     - controller-node-pool
        #       #             topologyKey: "kubernetes.io/hostname"
        #       #     topologySpreadConstraints:
        #       #       - maxSkew: 1
        #       #         topologyKey: topology.kubernetes.io/zone
        #       #         whenUnsatisfiable: DoNotSchedule
        #       #         labelSelector:
        #       #           matchLabels:
        #       #             strimzi.io/name: movies-app-broker
        #       #             strimzi.io/pool-name: controller-node-pool
        #   - name: broker-node-pool
        #     spec:
        #       replicas: 3
        #       roles:
        #         - broker
        #       resources:
        #         requests:
        #           memory: 256Mi
        #           cpu: 500m
        #         limits:
        #           memory: 1Gi
        #           cpu: "1"
        #       storage:
        #         type: jbod
        #         volumes:
        #           - id: 0
        #             type: persistent-claim
        #             size: 10Gi
        #             deleteClaim: false
        #       # template:
        #       #   pod:
        #       #     affinity:
        #       #       podAntiAffinity:
        #       #         requiredDuringSchedulingIgnoredDuringExecution:
        #       #           - labelSelector:
        #       #               matchExpressions:
        #       #                 - key: strimzi.io/pool-name
        #       #                   operator: In
        #       #                   values:
        #       #                     - broker-node-pool
        #       #             topologyKey: "kubernetes.io/hostname"
        #       #     topologySpreadConstraints:
        #       #       - maxSkew: 1
        #       #         topologyKey: topology.kubernetes.io/zone
        #       #         whenUnsatisfiable: DoNotSchedule
        #       #         labelSelector:
        #       #           matchLabels:
        #       #             strimzi.io/name: movies-app-broker
        #       #             strimzi.io/pool-name: broker-node-pool
        topics:
          - name: actors
            spec:
              replicas: 3
              partitions: 12
          - name: directors
            spec:
              replicas: 3
              partitions: 6
          - name: movies
            spec:
              replicas: 3
              partitions: 6
          - name: producers
            spec:
              replicas: 3
              partitions: 12
          - name: stunts
            spec:
              replicas: 3
              partitions: 24

        users:
          - name: kafka-console
            spec:
              authentication:
                type: scram-sha-512

        clientApp:
          namespace: movies-app

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
