apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - behavior: create
    files:
      - kafka-metrics-config.yaml
    name: kafka-metrics
patches:
  - path: Kafka_broker.merge.yaml
replacements:
  - source:
      fieldPath: metadata.name
      kind: ConfigMap
      name: kafka-metrics
    targets:
      - fieldPaths:
          - spec.kafka.metricsConfig.valueFrom.configMapKeyRef.name
        select:
          kind: Kafka
          name: broker
