apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
namespace: kafka-console-dex
resources:
  - ClusterRole_kafka-console-dex.yaml
  - ClusterRoleBinding_kafka-console-dex.yaml
  - Secret_kafka-console-dex.yaml
  - Deployment_kafka-console-dex.yaml
  - Service_kafka-console-dex.yaml
  - Ingress_kafka-console-dex.yaml
components:
  - ../openshift-oidc
# - path: Console_kafka-console.merge.yaml
patches:
  - patch: |-
      - op: add
        path: /metadata/annotations/serviceaccounts.openshift.io~1oauth-redirecturi.dex
        value: https://console-dex.apps-crc.testing/callback
    target:
      kind: ServiceAccount
      name: openshift-oidc-provider-sa
