apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cluster-ca
spec:
  secretName: cluster-ca
  issuerRef:
    name: self-signer
    kind: ClusterIssuer
  commonName: "ca.self-signer.cert-manager"
  isCA: true
