apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: music-app-kafka
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: music-app-kafka
    server: https://kubernetes.default.svc
  project: music-app
  source:
    path: app-config/apps/streams-kafka
    repoURL: https://github.com/ryan-highley/rh-streams-keycloak-certmgr-gitops
    helm:
      namespace: music-app-kafka
      releaseName: music-app
      valuesObject:

        global:
          cluster:
            name: music-app-broker

        cluster:
          spec:
            kafka:
              authorization:
                type: simple
                superUsers:
                  - CN=kafka-cli
                  - kafka-console
              listeners:
                - name: tls
                  port: 9093
                  type: internal
                  tls: true
                  authentication:
                    type: tls
                  networkPolicyPeers:
                    - namespaceSelector:
                        matchLabels:
                          kubernetes.io/metadata.name: music-app
                - name: console
                  port: 9094
                  type: internal
                  tls: true
                  authentication:
                    type: scram-sha-512
                  networkPolicyPeers:
                    - namespaceSelector:
                        matchLabels:
                          kubernetes.io/metadata.name: kafka-console

        topics:
          - name: albums
            spec:
              replicas: 3
              partitions: 12
          - name: artists
            spec:
              replicas: 3
              partitions: 24
          - name: bands
            spec:
              replicas: 3
              partitions: 12
          - name: producers
            spec:
              replicas: 3
              partitions: 24
          - name: songs
            spec:
              replicas: 3
              partitions: 48

        clientApp:
          namespace: music-app

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
