apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../cluster-config/profiles/bells-and-whistles
  - ../../app-config/profiles/multi-cluster-kafka-keycloak
patches:
  - patch: |-
      - op: replace
        path: /spec/hostname/hostname
        value: https://keycloak-service-keycloak.apps.ocp4.rhighley.remote.csb
    target:
      kind: Keycloak
      name: keycloak
