apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: smallstep-apps
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  generators:
    - list:
        elements:
          - name: step-certificates
          - name: step-issuer
  template:
    metadata:
      name: 'smallstep-apps-{{.name}}'
    spec:
      project: app-config
      source:
        chart: '{{.name}}'
        repoURL: https://smallstep.github.io/helm-charts
        targetRevision: HEAD
      helm:
        releaseName: '{{.name}}'
      destination:
        namespace: step-ca
        server: https://kubernetes.default.svc
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
