  # - Certificate_cert-issuer.yaml
  # - Issuer_cert-issuer.yaml
  # - Certificate_kafka-client-cert.yaml
resources:
  - Deployment_kafka-client.yaml
generatorOptions:
  disableNameSuffixHash: true
  # - name: kafka-client-cert-secret-keystore
  #   behavior: create
  #   type: Opaque
  #   literals:
  #     - password=not-terribly-secure
secretGenerator:
  - files:
      - kafka-client-config.properties
    name: kafka-client-config
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
