kind: Secret
apiVersion: v1
metadata:
  name: console-dex
stringData:
  config.yaml: |
    issuer: https://console-dex.apps-crc.testing

    storage:
      type: kubernetes
      config:
        inCluster: true

    web:
      http: 0.0.0.0:5556
      allowedOrigins: ['*']

    oauth2:
      skipApprovalScreen: true

    staticClients:
    - id: kafka-console
      name: 'Kafka Console'
      secret: shhh-kafka-console
      redirectURIs:
      - 'https://console-kafka-console.apps-crc.testing/api/auth/callback/oidc'

    connectors:
    - type: openshift
      id: openshift
      name: OpenShift
      config:
        # OpenShift API, e.g. `https://api.example.com:6443`
        # Get from kubectl via `kubectl config view --minify=true --flatten=false -o json | jq -r .clusters[0].cluster.server`
        issuer: https://kubernetes.default.svc

        # OpenShift root CA
        rootCA: /etc/ssl/openshift.pem

        # Communicate to OpenShift without validating SSL certificates
        insecureCA: false

        # Credentials can be string literals or pulled from the environment.
        clientID: ${OPENSHIFT_OAUTH_CLIENT_ID}
        clientSecret: ${OPENSHIFT_OAUTH_CLIENT_SECRET}

        # Optional list of required groups a user must be a member of
        groups: []

        # Redirect to the console's callback following authentication
        redirectURI: https://console-dex.apps-crc.testing/callback
