---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: console-dex
  annotations:
    serviceaccounts.openshift.io/oauth-redirecturi.dex: https://console-dex-kafka-console-dex.apps-crc.testing/callback
