apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/apicurio-registry-3.openshift-operators: ''
  name: apicurio-registry-3
  namespace: openshift-operators
spec:
  channel: 3.x
  installPlanApproval: Automatic
  name: apicurio-registry-3
  source: redhat-operators
  sourceNamespace: openshift-marketplace
