apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
components:
  - ../dual-role-node-pool
patches:
  - path: Kafka_broker.patch.yaml
    target:
      kind: Kafka
      name: broker
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: KafkaNodePool
      name: node-pool
