apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: operators
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  generators:
    - list:
        elements:
          - name: amq-broker-rhel9
            path: cluster-config/components/operators/amq-broker-rhel9
          - name: openshift-cert-manager
            path: cluster-config/components/operators/openshift-cert-manager
          - name: rh-keycloak
            path: cluster-config/components/operators/rh-keycloak
          - name: amq-streams
            path: cluster-config/components/operators/amq-streams
          - name: streams-console
            path: cluster-config/components/operators/streams-console
  template:
    metadata:
      name: 'operators-{{.name}}'
    spec:
      project: cluster-config
      source:
        path: '{{.path}}'
        repoURL: https://github.com/ryan-highley/rh-streams-keycloak-certmgr-gitops
      destination:
        namespace: openshift-gitops
        server: https://kubernetes.default.svc
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
