apiVersion: builtin
kind: ReplacementTransformer
metadata:
  name: job-cluster-name-repl-xform
replacements:
  - source:
      kind: Kafka
      name: broker
      fieldPath: metadata.name
    targets:
      - select:
          kind: Job
          name: kafka-ca-admin
        fieldPaths:
          - spec.template.spec.containers.[name=processor].env.[name=CLUSTER_NAME].value
