apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  instances: 1
  http:
    tlsSecret: keycloak-tls-secret
  networkPolicy:
    enabled: true
  hostname:
    hostname: https://localhost:8443
    