apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  instances: 1
  http:
    tlsSecret: keycloak-tls-secret
  networkPolicy:
    enabled: true
  hostname:
    hostname: https://localhost:8443
  resources:
    requests:
      memory: 256Mi
      cpu: 250m
    limits:
      memory: 512Mi
      cpu: '1'
