apiVersion: v2
name: step-ca-acme
description: A Helm chart for deploying an internal step-ca instance with an ACME issuer
type: application
version: 0.1.0

dependencies:
  - name: step-certificates
    repository: https://smallstep.github.io/helm-charts
    version: 1.30.1
