apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.deployment.name }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "{{ .Values.deployment.name }}"
  template:
    metadata:
      labels:
        app: "{{ .Values.deployment.name }}"
    spec:
      serviceAccountName: "{{ .Values.deployment.name }}"
      volumes:
      - name: config
        secret:
          secretName: "{{ .Values.deployment.name }}"
          items:
          - key: config.yaml
            path: config.yaml
      - name: openshift-ca
        configMap:
          name: kube-root-ca.crt
          items:
          - key: ca.crt
            path: openshift.pem
      containers:
      - image: ghcr.io/dexidp/dex:v2.32.0
        name: dex
        command: ["/usr/local/bin/dex", "serve", "/etc/dex/cfg/config.yaml"]

        ports:
        - name: http
          containerPort: 5556

        volumeMounts:
        - name: config
          mountPath: /etc/dex/cfg
        - name: openshift-ca
          mountPath: /etc/ssl/openshift.pem
          subPath: openshift.pem

        env:
        - name: OPENSHIFT_OAUTH_CLIENT_ID
          value: "system:serviceaccount:{{ .Values.deployment.namespace }}:{{ .Values.deployment.name }}"
        - name: OPENSHIFT_OAUTH_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: "{{ .Values.deployment.name }}-token"
              key: token

        readinessProbe:
          httpGet:
            path: /healthz
            port: 5556
            scheme: HTTP

        resources:
          requests:
            cpu: 125m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
