kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: '{{ .Values.deployment.name }}'
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    route.openshift.io/termination: edge
spec:
  defaultBackend:
    service:
      name: '{{ .Values.deployment.name }}'
      port:
        number: 5556
  rules:
    - host: '{{ .Values.deployment.name }}.{{ .Values.baseDomain }}'
      http:
        paths:
          - pathType: ImplementationSpecific
            backend:
              service:
                name: '{{ .Values.deployment.name }}'
                port:
                  number: 5556
