apiVersion: v1
kind: Secret
metadata:
  name: '{{ .Values.deployment.name }}-token'
  annotations:
    kubernetes.io/service-account.name: '{{ .Values.deployment.name }}'
type: kubernetes.io/service-account-token
data: {}
