apiVersion: v1
kind: ServiceAccount
metadata:
  name: '{{ .Values.deployment.name }}'
  annotations:
    serviceaccounts.openshift.io/oauth-redirecturi.dex: https://{{ .Values.deployment.name }}.{{ .Values.baseDomain }}/callback
secrets:
  - name: '{{ .Values.deployment.name }}-token'
