apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: broker
  annotations:
    strimzi.io/node-pools: enabled
    strimzi.io/kraft: enabled
spec:
  kafka:
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
    authorization:
      type: simple
      superUsers: []
    listeners:
      - name: tls
        port: 9093
        type: internal
        tls: true
    version: "4.0.0"
    metadataVersion: "4.0-IV3"
  entityOperator:
    topicOperator: {}
    userOperator: {}
