apiVersion: builtin
kind: PatchTransformer
metadata:
  name: keycloak-postgresql-cluster-config-operators-patch.yaml
target:
  kind: ApplicationSet
  name: cluster-config-operators
patch: |-
  # Add the rh-keycloak generator element
  - op: add
    path: /spec/generators/0/list/elements/-
    value:
      name: rh-keycloak
      namespace: keycloak
      path: cluster-config/components/operators/rh-keycloak
