apiVersion: builtin
kind: PatchTransformer
metadata:
  name: keycloak-postgresql-cluster-apps-patch.yaml
target:
  kind: ApplicationSet
  name: cluster-apps
patch: |-
  # Test that element 1 has the name 'keycloak'
  - op: test
    path: /spec/generators/0/list/elements/1/name
    value: keycloak
  # Replace the path of element 1
  - op: replace
    path: /spec/generators/0/list/elements/1/path
    value: cluster-config/cluster-apps/keycloak/overlays/keycloak-postgresql
