apiVersion: console.streamshub.github.com/v1alpha1
kind: Console
metadata:
  name: kafka-console
spec:
  hostname: console-kafka-console.apps.pp3cdmsj.westus.aroapp.io
  kafkaClusters:
    - name: movies-app-broker
      namespace: movies-app-kafka
      listener: tls
      credentials:
        kafkaUser:
          name: kafka-console
    - name: music-app-broker
      namespace: music-app-kafka
      listener: tls
      credentials:
        kafkaUser:
          name: kafka-console
