apiVersion: console.streamshub.github.com/v1alpha1
kind: Console
metadata:
  name: kafka-console
spec:
  hostname: console-kafka-console.apps.pp3cdmsj.westus.aroapp.io
  security:
    oidc:
      authServerUrl: https://openshift.default.svc/.well-known/oauth-authorization-server
      clientId: kafka-console
      clientSecret:
        valueFrom:
          secretKeyRef:
            name: kafka-console-client-secret
            key: clientSecret
      subjects:
        - claim: groups
          include:
            - kafka-admins
          roleNames:
            - kafka-admins
        - claim: groups
          include:
            - kafka-developers
          roleNames:
            - kafka-developers
        - claim: groups
          include:
            - music-app-admins
          roleNames:
            - music-app-admins
        - claim: groups
          include:
            - music-app-admins
          roleNames:
            - music-app-admins
        - claim: groups
          include:
            - music-app-developers
          roleNames:
            - music-app-developers
        - claim: groups
          include:
            - movies-app-admins
          roleNames:
            - movies-app-admins
        - claim: groups
          include:
            - movies-app-developers
          roleNames:
            - movies-app-developers
      roles:
        - name: kafka-admins
          rules:
            - resources:
                - kafkas
              privileges:
                - 'ALL'
        - name: kafka-developers
          rules:
            - resources:
                - kafkas
              privileges:
                - 'READ'
                - 'WRITE'
                - 'DESCRIBE'
                - 'DESCRIBECONFIGS'
                - 'IDEMPOTENTWRITE'
        - name: music-app-admins
          rules:
            - resources:
                - kafkas
              resourceNames:
                - music-app-broker
              privileges:
                - 'ALL'
        - name: music-app-developers
          rules:
            - resources:
                - kafkas
              resourceNames:
                - music-app-broker
              privileges:
                - 'READ'
                - 'WRITE'
                - 'DESCRIBE'
                - 'DESCRIBECONFIGS'
                - 'IDEMPOTENTWRITE'
        - name: movies-app-admins
          rules:
            - resources:
                - kafkas
              resourceNames:
                - movies-app-broker
              privileges:
                - 'ALL'
        - name: movies-app-developers
          rules:
            - resources:
                - kafkas
              resourceNames:
                - movies-app-broker
              privileges:
                - 'READ'
                - 'WRITE'
                - 'DESCRIBE'
                - 'DESCRIBECONFIGS'
                - 'IDEMPOTENTWRITE'
  kafkaClusters:
    - name: movies-app-broker
      namespace: movies-app-kafka
      listener: console
      credentials:
        kafkaUser:
          name: kafka-console
    - name: music-app-broker
      namespace: music-app-kafka
      listener: console
      credentials:
        kafkaUser:
          name: kafka-console
