apiVersion: console.streamshub.github.com/v1alpha1
kind: Console
metadata:
  name: console
spec:
  hostname: console-kafka-console.apps-crc.testing
  security:
    oidc:
      authServerUrl: https://console-dex.apps-crc.testing
      clientId: kafka-console
      clientSecret:
        valueFrom:
          secretKeyRef:
            name: kafka-console-client-secret
            key: clientSecret
      trustStore:
        type: PEM
        content:
          valueFrom:
            configMapKeyRef:
              name: kube-root-ca.crt
              key: ca.crt
    subjects:
      - claim: groups
        include:
          - kafka-admins
        roleNames:
          - kafka-admins
      - claim: groups
        include:
          - kafka-developers
        roleNames:
          - kafka-developers
      - claim: groups
        include:
          - kafka-admins
          - music-app-admins
        roleNames:
          - music-app-admins
      - claim: groups
        include:
          - music-app-developers
        roleNames:
          - kafka-developers
          - music-app-developers
      - claim: groups
        include:
          - kafka-admins
          - movies-app-admins
        roleNames:
          - movies-app-admins
      - claim: groups
        include:
          - kafka-developers
          - movies-app-developers
        roleNames:
          - movies-app-developers
    roles:
      - name: kafka-admins
        rules:
          - resources:
              - kafkas
            resourceNames:
              - "*"
            privileges:
              - ALL
      - name: kafka-developers
        rules:
          - resources:
              - kafkas
            resourceNames:
              - "*"
            privileges:
              - ALL
      - name: movies-app-admins
        rules:
          - resources:
              - kafkas
            resourceNames:
              - movies-app-broker
            privileges:
              - ALL
      - name: movies-app-developers
        rules:
          - resources:
              - kafkas
            resourceNames:
              - movies-app-broker
            privileges:
              - ALL
      - name: music-app-admins
        rules:
          - resources:
              - kafkas
            resourceNames:
              - music-app-broker
            privileges:
              - ALL
      - name: music-app-developers
        rules:
          - resources:
              - kafkas
            resourceNames:
              - music-app-broker
            privileges:
              - ALL
  kafkaClusters:
    - name: movies-app-broker
      namespace: movies-app-kafka
      listener: console
      credentials:
        kafkaUser:
          name: kafka-console
      security:
        roles:
          - name: movies-app-admins
            rules:
              - resources:
                  - topics
                  - topics/records
                  - consumerGroups
                  - rebalances
                  - nodes/configs
                  - nodes
                privileges:
                  - GET
                  - LIST
              - resources:
                  - consumerGroups
                  - rebalances
                privileges:
                  - UPDATE
          - name: movies-app-developers
            rules:
              - resources:
                  - topics
                  - topics/records
                  - consumerGroups
                  - rebalances
                privileges:
                  - GET
                  - LIST
    - name: music-app-broker
      namespace: music-app-kafka
      listener: console
      credentials:
        kafkaUser:
          name: kafka-console
      security:
        roles:
          - name: music-app-admins
            rules:
              - resources:
                  - topics
                  - topics/records
                  - consumerGroups
                  - rebalances
                  - nodes/configs
                  - nodes
                privileges:
                  - GET
                  - LIST
              - resources:
                  - consumerGroups
                  - rebalances
                privileges:
                  - UPDATE
          - name: music-app-developers
            rules:
              - resources:
                  - topics
                  - topics/records
                  - consumerGroups
                  - rebalances
                privileges:
                  - GET
                  - LIST
