apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openshift-gitops
resources:
  - ../../base
  - movies-app/
  - music-app/
  - kafka-console/
patches:
  - patch: |-
      - op: replace
        path: /spec/source/path
        value: argocd/app-config/profiles/multi-cluster-kafka
    target:
      kind: Application
      name: app-config
