resources:
  - ../../base

patches:
  - target:
      kind: Application
      name: cluster-config
    patch: |-
      - op: replace
        path: /spec/source/path
        value: argocd/cluster-config/profiles/cert-manager-custom-ca

transformers:
  - transformers/
