resources:
  - ../../../base/node-pool
patches:
  - options:
      allowNameChange: true
    patch: |-
      - op: replace
        path: /metadata/name
        value: controller-node-pool
      - op: replace
        path: /spec/roles
        value:
          - controller
    target:
      kind: KafkaNodePool
      name: node-pool
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
