{{- with .Values.cluster -}}
apiVersion: kafka.strimzi.io/v1
kind: Kafka
metadata:
  name: {{ .name }}
  annotations:
    strimzi.io/node-pools: enabled
    strimzi.io/kraft: enabled
spec:
  {{- toYaml .spec | nindent 2 }}
{{- end }}
