apiVersion: v1
kind: Secret
metadata:
  name: openshift-oidc-provider-token
  annotations:
    kubernetes.io/service-account.name: openshift-oidc-provider-sa
type: kubernetes.io/service-account-token
data: {}
