apiVersion: console.streamshub.github.com/v1alpha1
kind: Console
metadata:
  name: console
spec:
  security:
    oidc:
      authServerUrl: https://keycloak-service.keycloak.svc:8443/realms/openshift-oidc
      clientId: kafka-console
      clientSecret:
        value: SnrI7oimbWw5jxpToX9ou1AK9MYhMFa2
      trustStore:
        type: PEM
        content:
          valueFrom:
            configMapKeyRef:
              name: kube-root-ca.crt
              key: ca.crt
