namespace: keycloak

resources:
  - ../default
  - Secret_postgresql-credentials.yaml
  - PersistentVolumeClaim_postgresql-db-data.yaml
  - Deployment_postgresql-db.yaml
  - Service_postgresql-db.yaml

patches:
  - target:
      kind: Keycloak
      name: keycloak
    patch: |-
      - op: add
        path: /spec/db
        value:
          vendor: postgres
          host: postgresql-db.keycloak.svc
          usernameSecret:
            name: postgresql-credentials
            key: POSTGRES_USER
          passwordSecret:
            name: postgresql-credentials
            key: POSTGRES_PASSWORD
