apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - patch: |-
      - op: replace
        path: /spec/source/path
        value: argocd/cluster-config/profiles/keycloak-postgresql
    target:
      kind: Application
      name: cluster-config
transformers:
  - transformers/
