apiVersion: v2
name: streams-kafka
description: A Helm chart for creating Red Hat Streams for Apache Kafka applications
type: application
version: 0.1.0
dependencies:
  - name: cluster-issuer
    condition: cluster-issuer.enabled
  - name: keycloak
    condition: keycloak.enabled
